python train.py \
	--save_path saved_checkpoints/model-50/merge_concat-pool1line-2sides \
	--epochs 35 \
	--loss_margin 1 \
	--dev_every 600 \
	--d_rel_embed 158 \
    	--d_hidden 186 \
	--n_layers 2 \
	--channel_size 8 \
	--conv_kernel_1 3 \
	--conv_kernel_2 3 \
	--pool_kernel_1 21 \
	--pool_kernel_2 1 \
	--gpu 6 \
	--lr 0.0005 \
	--train_file data/train.relation_ranking.all-50.pt \
	--valid_file data/valid.relation_ranking.all-50.pt \
	--rnn_type gru 
